# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Rust crates
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build Rust (FFI bindings are required for tests)
      run: cargo build
      env:
        CARGO_TERM_COLOR: always

    - name: Build
      run: go build -v ./...
      env:
        GOEXPERIMENT: rangefunc

    - name: Test
      run: go test -v ./...
      env:
        GOEXPERIMENT: rangefunc
